### PR TITLE
Vendored deps

### PR DESCRIPTION
**Pull request by scottferg**
@foresmac

### CODE REVIEW

**Comment by foresmac** [comment]
"Sorry, we could not display the entire diff because it was too big."

**Comment by scottferg** [comment]
I'll make it bigger next time

**Comment by foresmac** [comment]
Why vendor stdlib stuff like image?

**Comment by scottferg** [comment]
Where do you see that? https://github.com/scottferg/vip/blob/master/vendor/vendor.json

**Comment by scottferg** [comment]
`golang.org/x` packages are considered external but stdlib would always be ignored since it's always in your GOPATH

**Comment by foresmac** [comment]
`code.google.com/p/go.image/bmp`, for instance. But I might be misremembering where that code comes from. I have a lot of refactoring I want to do on this project to use some stuff from Go 1.5 & 1.6 and swap out a different libvips binding anyhowways. I'll have to read up more on how the vending works since I honestly only have a vague idea of it...

**Comment by foresmac** [comment]
LGTM pending build status.

**Comment by scottferg** [comment]
That should probably change to `golang.org/x/image/bmp` at some point, I'll add that

**Comment by foresmac** [comment]
"[error] Unable to validate Yaml checksum. This means that secrets will not be injected. In addition the Deploy and Notify steps will not be executed. To resolve this please regenerate the secrets file. "

**Comment by foresmac** [comment]
```
https://cvr.vokal.io/coverage?commit=$DRONE_COMMIT&owner=$REPO_OWNER&repo=$REPO_NAME&coveragetype=cobertura
```
Pretty sure it should be `coveragetype=gocover`

**Comment by scottferg** [comment]
Weird, @projectweekend I'm getting "Not Authorized" on the Secrets tab for vip. Did something change when you were debugging it yesterday?

**Comment by scottferg** [comment]
@foresmac fixed

Whatever's messing up secrets on Drone needs to be resolved before this can be merged though

**Comment by projectweekend** [comment]
You're already an admin on Drone...same as me...and I can see the tab

**Comment by scottferg** [comment]
@projectweekend same result even with a new `.drone.sec`. Can you try generating one?

**Comment by scottferg** [comment]
Debian has been having repo issues lately too, so you can safely ignore that build failure

**Pull request merged**
