### PR TITLE
No c lib

### PR DESCRIPTION
**Pull request by WorkHorseIndustries**
Changed some variable names and added some tests.

### CODE REVIEW

**Comment by WorkHorseIndustries** [comment]
@vokal/systems @foresmac

**Comment by foresmac** [comment]
LGTM. Can you get it set up so CVR is reporting to github?

**Comment by projectweekend** [comment]
LGTM

**Comment by WorkHorseIndustries** [comment]
@foresmac sure, I'll put that on the list.

**Pull request merged**
