### PR TITLE
Let's try and get cvr working

### PR DESCRIPTION
**Pull request by foresmac**
@vokal/systems
@jrit

### CODE REVIEW

**Comment by jrit** [comment]
Needs `&removepath=vip/`

**Comment by jrit** [comment]
Was this with multiple modes?

**Comment by foresmac** [comment]
yeah

**Comment by foresmac** [comment]
It should basically be exactly what I sent over in the `coverage.txt` file via email.

**Comment by jrit** [comment]
OK, good, looks like it is parsing it correctly. I don't understand why sometimes Go considers the closing brace part of the covered code and sometimes does not. But, it looks like it considers the closing brace to be covered if the block is entered, so maybe it skews the percent a little, but it doesn't appear to be "wrong" in the sense that it says something isn't covered when it is. The percent likely won't agree with what Go Cover says the percent is as a result though.

**Comment by jrit** [comment]
LGTM, though obviously you want to reduce the passing threshold if you'd like to see the build pass

**Pull request merged**
